config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chapter#index'
  resources :chapter, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contentful_chapter.rb
class ContentfulChapter < ContentfulModel::Base
	self.content_type_id = "formationChapter"
	
	unless Rails.env == 'production'
		ContentfulModel.use_preview_api = true
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapter_controller.rb
class ChapterController < ApplicationController
  def index
    @entries = ContentfulChapter.all.load
    @test_string = "This is a test"
  end
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    @entry = ContentfulChapter.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chapter/index.html.erb
<h1>Here's the list of your first 100 entries:</h1>
<% @entries.each do |entry| %>
<ul>
	<li><%= link_to(entry.title, chapter_path(entry.id)) %></li>
</ul>
<% end %>
<div id="app"></div>
<script>
  let testString = "<%= @test_string %>"
</script>
<%= javascript_pack_tag "hello_react" %>

app/views/chapter/show.html.erb
<h1><%= @entry.title %></h1>
<div class='introduction' style="color: blue;">
  <%= @markdown.render(@entry.introduction).html_safe %>
</div>
<hr>
<div class="body">
  <%= @markdown.render(@entry.body).html_safe %>
</div>
<hr>
<div class="from-the-field">
  <%= @markdown.render(@entry.fromTheField).html_safe %>
</div>
<hr>
<div class="thoughts-to-ponder">
  <%= @markdown.render(@entry.thoughtsToPonder).html_safe %>
</div>
<hr>
<div class="faq">
  <%= @markdown.render(@entry.faq).html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MissionersFormation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>